services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: S3-notification-service-dev
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}\
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
