"""add s3 path and delivery date

Revision ID: 053c741bd6a1
Revises: 7f46769eda3f
Create Date: 2024-11-28 19:54:54.296344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053c741bd6a1'
down_revision: Union[str, None] = '7f46769eda3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('s3_path', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'delivery_date')
    op.drop_column('batches', 's3_path')
    # ### end Alembic commands ###
