"""user

Revision ID: 0a9fce69c4a0
Revises: d01cb9b8e78d
Create Date: 2024-11-08 21:43:11.041002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9fce69c4a0'
down_revision: Union[str, None] = 'd01cb9b8e78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pre Processing Files', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('Pre Processing Files', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_constraint('Pre Processing Files_user_id_fkey', 'Pre Processing Files', type_='foreignkey')
    op.drop_column('Pre Processing Files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pre Processing Files', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Pre Processing Files_user_id_fkey', 'Pre Processing Files', 'users', ['user_id'], ['id'])
    op.drop_column('Pre Processing Files', 'user_name')
    op.drop_column('Pre Processing Files', 'user_email')
    # ### end Alembic commands ###
