"""add type of validation error

Revision ID: 121796f51905
Revises: 9e4d1508a70d
Create Date: 2024-12-04 20:53:36.729327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "121796f51905"
down_revision: Union[str, None] = "9e4d1508a70d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("SCHEMA", "S3_LINK", "DUPLICATION", name="validationerrortypeenum").create(op.get_bind())
    # op.drop_index('ix_activity_logs_details', table_name='activity_logs', postgresql_using='gin')
    # op.drop_index('ix_activity_logs_id', table_name='activity_logs')
    # op.drop_table('activity_logs')
    op.add_column(
        "validation_errors",
        sa.Column(
            "type",
            postgresql.ENUM("SCHEMA", "S3_LINK", "DUPLICATION", name="validationerrortypeenum", create_type=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validation_errors", "type")
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="activity_logs_user_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="activity_logs_pkey"),
    )
    op.create_index("ix_activity_logs_id", "activity_logs", ["id"], unique=False)
    op.create_index("ix_activity_logs_details", "activity_logs", ["details"], unique=False, postgresql_using="gin")
    sa.Enum("SCHEMA", "S3_LINK", "DUPLICATION", name="validationerrortypeenum").drop(op.get_bind())
    # ### end Alembic commands ###
