"""Added validation error - Penguin formatting

Revision ID: 230497bc78c3
Revises: bf3a4b3d6f7a
Create Date: 2025-01-06 16:58:22.227793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '230497bc78c3'
down_revision: Union[str, None] = 'bf3a4b3d6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='validationerrortypeenum',
        new_values=['SCHEMA', 'S3_LINK', 'DUPLICATION', 'JSON_FORMATTING', 'TASK_CREATION', 'TASK_PROCESSING', 'PENGUIN_FORMATTING'],
        affected_columns=[TableReference(table_schema='public', table_name='validation_errors', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='validationerrortypeenum',
        new_values=['SCHEMA', 'S3_LINK', 'DUPLICATION', 'JSON_FORMATTING', 'TASK_CREATION', 'TASK_PROCESSING'],
        affected_columns=[TableReference(table_schema='public', table_name='validation_errors', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
