"""flag added for files

Revision ID: 252d68d09b40
Revises: c7cf6c8b31e7
Create Date: 2024-11-20 20:05:41.158586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252d68d09b40'
down_revision: Union[str, None] = 'c7cf6c8b31e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_processing_file_json', sa.Column('is_raw_data', sa.Boolean(), nullable=True))
    op.add_column('pre_processing_file_json', sa.Column('is_apple_format', sa.Boolean(), nullable=True))
    op.add_column('pre_processing_file_json', sa.Column('is_error_free', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_processing_file_json', 'is_error_free')
    op.drop_column('pre_processing_file_json', 'is_apple_format')
    op.drop_column('pre_processing_file_json', 'is_raw_data')
    # ### end Alembic commands ###
