"""remove batch 

Revision ID: 26ded442b835
Revises: 9adee15b7c76
Create Date: 2024-11-25 04:24:36.074727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ded442b835'
down_revision: Union[str, None] = '9adee15b7c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.drop_column('pre_processing_file_json', 'is_apple_format')
    op.drop_column('pre_processing_file_json', 'is_raw_data')
    op.drop_column('pre_processing_file_json', 'is_error_free')
    op.drop_column('pre_processing_files', 'batch_id')
    op.drop_column('validation_errors', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_errors', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_files', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_file_json', sa.Column('is_error_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_file_json', sa.Column('is_raw_data', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_file_json', sa.Column('is_apple_format', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
