"""delivery_id can be null

Revision ID: 270c5fde3cfb
Revises: a22eb1633da9
Create Date: 2024-12-10 16:54:45.606275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270c5fde3cfb'
down_revision: Union[str, None] = 'a22eb1633da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_errors', 'delivery_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_errors', 'delivery_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
