"""add validation type

Revision ID: 374a8685a823
Revises: e02f0477cadf
Create Date: 2024-12-09 23:08:41.084185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '374a8685a823'
down_revision: Union[str, None] = 'e02f0477cadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='validationerrortypeenum',
        new_values=['SCHEMA', 'S3_LINK', 'DUPLICATION', 'JSON_FORMATTING'],
        affected_columns=[TableReference(table_schema='public', table_name='validation_errors', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='validationerrortypeenum',
        new_values=['SCHEMA', 'S3_LINK', 'DUPLICATION'],
        affected_columns=[TableReference(table_schema='public', table_name='validation_errors', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
