"""status

Revision ID: 508d8fd79738
Revises: 0a9fce69c4a0
Create Date: 2024-11-09 00:15:54.635617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '508d8fd79738'
down_revision: Union[str, None] = '0a9fce69c4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('IN_PROGRESS', 'COMPLETED', name='statusenum').create(op.get_bind())
    op.add_column('Pre Processing Files', sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='statusenum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pre Processing Files', 'status')
    sa.Enum('IN_PROGRESS', 'COMPLETED', name='statusenum').drop(op.get_bind())
    # ### end Alembic commands ###