"""delivery-id in place of deliverable_id

Revision ID: 598941f5bee0
Revises: a47dfbbde6f6
Create Date: 2024-11-21 00:05:01.810640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598941f5bee0'
down_revision: Union[str, None] = 'a47dfbbde6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivered_ids', sa.Column('delivery_id', sa.String(length=100), nullable=False))
    op.drop_index('ix_delivered_ids_deliverable_id', table_name='delivered_ids')
    op.create_index(op.f('ix_delivered_ids_delivery_id'), 'delivered_ids', ['delivery_id'], unique=True)
    op.drop_column('delivered_ids', 'deliverable_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivered_ids', sa.Column('deliverable_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_delivered_ids_delivery_id'), table_name='delivered_ids')
    op.create_index('ix_delivered_ids_deliverable_id', 'delivered_ids', ['deliverable_id'], unique=True)
    op.drop_column('delivered_ids', 'delivery_id')
    # ### end Alembic commands ###
