"""add new workstream

Revision ID: 70d241a3db8b
Revises: f9b93c8b2681
Create Date: 2024-12-16 19:18:19.078117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '70d241a3db8b'
down_revision: Union[str, None] = 'f9b93c8b2681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workstreamenum',
        new_values=['RLHF_VISION', 'IMAGE_EVAL', 'SFT_REASONING', 'RLHF_TEXT'],
        affected_columns=[TableReference(table_schema='public', table_name='batches', column_name='workstream')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workstreamenum',
        new_values=['RLHF_VISION', 'IMAGE_EVAL', 'SFT_REASONING'],
        affected_columns=[TableReference(table_schema='public', table_name='batches', column_name='workstream')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
