"""added upload status

Revision ID: 7f46769eda3f
Revises: 71d54db922f0
Create Date: 2024-11-26 20:04:42.666632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f46769eda3f'
down_revision: Union[str, None] = '71d54db922f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('is_uploaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'is_uploaded')
    # ### end Alembic commands ###
