"""validation error flag

Revision ID: 88f25f2119c6
Revises: 11a8ade48cf8
Create Date: 2024-11-29 15:49:38.251076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f25f2119c6'
down_revision: Union[str, None] = '11a8ade48cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('has_validation_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'has_validation_error')
    # ### end Alembic commands ###
