"""batch

Revision ID: 94bf20743d52
Revises: 0d215c615047
Create Date: 2024-11-25 22:55:39.922587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94bf20743d52'
down_revision: Union[str, None] = '0d215c615047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='statusenum', create_type=False), nullable=True))
    op.add_column('batches', sa.Column('workstream_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'workstream', ['workstream_id'], ['id'])
    op.drop_constraint('pre_processing_files_workstream_id_fkey', 'pre_processing_files', type_='foreignkey')
    op.drop_column('pre_processing_files', 'status')
    op.drop_column('pre_processing_files', 'workstream_id')
    op.drop_column('pre_processing_files', 'user_email')
    op.drop_column('pre_processing_files', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_processing_files', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_files', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_files', sa.Column('workstream_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pre_processing_files', sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='statusenum', create_type=False), autoincrement=False, nullable=True))
    op.create_foreign_key('pre_processing_files_workstream_id_fkey', 'pre_processing_files', 'workstream', ['workstream_id'], ['id'])
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'workstream_id')
    op.drop_column('batches', 'status')
    op.drop_column('batches', 'user_email')
    op.drop_column('batches', 'user_name')
    # ### end Alembic commands ###
