"""batch id instead of file id in validation error

Revision ID: 9adee15b7c76
Revises: afc970dd1b2f
Create Date: 2024-11-25 04:01:30.630549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adee15b7c76'
down_revision: Union[str, None] = 'afc970dd1b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_level', sa.String(), nullable=False),
    sa.Column('log_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('validation_errors', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.drop_constraint('validation_errors_preprocessing_file_id_fkey', 'validation_errors', type_='foreignkey')
    op.drop_column('validation_errors', 'preprocessing_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_errors', sa.Column('preprocessing_file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('validation_errors_preprocessing_file_id_fkey', 'validation_errors', 'pre_processing_files', ['preprocessing_file_id'], ['id'])
    op.drop_column('validation_errors', 'batch_id')
    op.drop_table('logs')
    # ### end Alembic commands ###
