"""remove failed reason

Revision ID: a22eb1633da9
Revises: e19766f518c0
Create Date: 2024-12-10 16:36:22.600635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22eb1633da9'
down_revision: Union[str, None] = 'e19766f518c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'failed_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('failed_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
