"""Configuration table added

Revision ID: b2d90aa1a8b2
Revises: c7fb9e8daa59
Create Date: 2024-12-04 21:59:03.908470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2d90aa1a8b2"
down_revision: Union[str, None] = "c7fb9e8daa59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_option",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("value", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_option_id"), "config_option", ["id"], unique=False)
    op.create_index(op.f("ix_config_option_name"), "config_option", ["name"], unique=True)
    # op.drop_index('ix_activity_logs_details', table_name='activity_logs', postgresql_using='gin')
    # op.drop_index('ix_activity_logs_id', table_name='activity_logs')
    # op.drop_table('activity_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("resource_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="activity_logs_user_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="activity_logs_pkey"),
    )
    op.create_index("ix_activity_logs_id", "activity_logs", ["id"], unique=False)
    op.create_index("ix_activity_logs_details", "activity_logs", ["details"], unique=False, postgresql_using="gin")
    op.drop_index(op.f("ix_config_option_name"), table_name="config_option")
    op.drop_index(op.f("ix_config_option_id"), table_name="config_option")
    op.drop_table("config_option")
    # ### end Alembic commands ###
