"""seperate table for json

Revision ID: bbba6d6c7f2b
Revises: cca612c9abca
Create Date: 2024-11-15 00:47:21.815643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbba6d6c7f2b'
down_revision: Union[str, None] = 'cca612c9abca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_processing_file_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preprocessing_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['preprocessing_file_id'], ['pre_processing_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_processing_file_json_id'), 'pre_processing_file_json', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_processing_file_json_id'), table_name='pre_processing_file_json')
    op.drop_table('pre_processing_file_json')
    # ### end Alembic commands ###
