"""seperate table for json

Revision ID: c7cf6c8b31e7
Revises: 6b84129bde89
Create Date: 2024-11-15 02:30:08.513273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7cf6c8b31e7'
down_revision: Union[str, None] = '6b84129bde89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_processing_files', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.drop_column('pre_processing_files', 'content')
    op.drop_index('ix_s3files_annotator_id', table_name='s3_files')
    op.create_index(op.f('ix_s3_files_annotator_id'), 's3_files', ['annotator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s3_files_annotator_id'), table_name='s3_files')
    op.create_index('ix_s3files_annotator_id', 's3_files', ['annotator_id'], unique=False)
    op.add_column('pre_processing_files', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('pre_processing_files', 'batch_id')
    # ### end Alembic commands ###
