"""error table

Revision ID: cca612c9abca
Revises: 508d8fd79738
Create Date: 2024-11-12 18:48:04.019483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cca612c9abca'
down_revision: Union[str, None] = '508d8fd79738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_processing_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('workstream_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='statusenum', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_processing_files_id'), 'pre_processing_files', ['id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preprocessing_file_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preprocessing_file_id'], ['pre_processing_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_id'), 'validation_errors', ['id'], unique=False)
    op.drop_index('ix_Pre Processing Files_id', table_name='Pre Processing Files')
    op.drop_table('Pre Processing Files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pre Processing Files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('workstream_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', name='statusenum', create_type=False), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstream.id'], name='Pre Processing Files_workstream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Pre Processing Files_pkey')
    )
    op.create_index('ix_Pre Processing Files_id', 'Pre Processing Files', ['id'], unique=False)
    op.drop_index(op.f('ix_validation_errors_id'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_pre_processing_files_id'), table_name='pre_processing_files')
    op.drop_table('pre_processing_files')
    # ### end Alembic commands ###
