"""workstream

Revision ID: d01cb9b8e78d
Revises: f2cbaecfb057
Create Date: 2024-11-08 20:34:57.390356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01cb9b8e78d'
down_revision: Union[str, None] = 'f2cbaecfb057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workstream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workstream_id'), 'workstream', ['id'], unique=False)
    op.add_column('Pre Processing Files', sa.Column('workstream_id', sa.Integer(), nullable=True))
    op.add_column('Pre Processing Files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Pre Processing Files', 'workstream', ['workstream_id'], ['id'])
    op.create_foreign_key(None, 'Pre Processing Files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Pre Processing Files', type_='foreignkey')
    op.drop_constraint(None, 'Pre Processing Files', type_='foreignkey')
    op.drop_column('Pre Processing Files', 'user_id')
    op.drop_column('Pre Processing Files', 'workstream_id')
    op.drop_index(op.f('ix_workstream_id'), table_name='workstream')
    op.drop_table('workstream')
    # ### end Alembic commands ###
