"""add validation type

Revision ID: e19766f518c0
Revises: 374a8685a823
Create Date: 2024-12-09 23:59:23.041930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'e19766f518c0'
down_revision: Union[str, None] = '374a8685a823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='validationerrortypeenum',
        new_values=['SCHEMA', 'S3_LINK', 'DUPLICATION', 'JSON_FORMATTING', 'TASK_CREATION', 'TASK_PROCESSING'],
        affected_columns=[TableReference(table_schema='public', table_name='validation_errors', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='validationerrortypeenum',
        new_values=['SCHEMA', 'S3_LINK', 'DUPLICATION', 'JSON_FORMATTING'],
        affected_columns=[TableReference(table_schema='public', table_name='validation_errors', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
