"""timestamp

Revision ID: f2cbaecfb057
Revises: b187cf788cfd
Create Date: 2024-11-07 02:37:32.890996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cbaecfb057'
down_revision: Union[str, None] = 'b187cf788cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pre Processing Files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Pre Processing Files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pre Processing Files', 'updated_at')
    op.drop_column('Pre Processing Files', 'created_at')
    # ### end Alembic commands ###
