"""comment

Revision ID: f9b93c8b2681
Revises: 270c5fde3cfb
Create Date: 2024-12-13 16:22:14.248476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f9b93c8b2681'
down_revision: Union[str, None] = '270c5fde3cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_errors', sa.Column('link', sa.String(), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workstreamenum',
        new_values=['RLHF_VISION', 'IMAGE_EVAL', 'SFT_REASONING'],
        affected_columns=[TableReference(table_schema='public', table_name='batches', column_name='workstream')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workstreamenum',
        new_values=['RLHF_VISION', 'IMAGE_EVAL'],
        affected_columns=[TableReference(table_schema='public', table_name='batches', column_name='workstream')],
        enum_values_to_rename=[],
    )
    op.drop_column('validation_errors', 'link')
    # ### end Alembic commands ###
