name: Frontend

on:
  push:
    paths:
      - "frontend/**"
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: 20
          cache: "npm"
      - name: Install & build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
